# Generated by Django 4.1.12 on 2023-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_author', models.CharField(max_length=40, verbose_name='اپراتور ثبت')),
                ('material_name', models.CharField(max_length=300, verbose_name='نام')),
                ('material_code', models.CharField(max_length=50, verbose_name='کد')),
                ('material_color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('material_quantity', models.PositiveIntegerField(null=True, verbose_name='موجودی')),
                ('material_location', models.CharField(max_length=50, verbose_name='انبار')),
                ('material_hall', models.CharField(max_length=20, verbose_name='سالن انبار')),
                ('material_unit', models.CharField(max_length=20, verbose_name='واحد')),
                ('material_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجودی / عدم موجودی')),
                ('row', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
            },
        ),
    ]
