# Generated by Django 4.1.12 on 2023-12-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_code',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_hall',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_location',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='material_quantity',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='row',
        ),
        migrations.AddField(
            model_name='materials',
            name='material_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material_author',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='اپراتور ثبت'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام ماده'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='واحد'),
        ),
    ]
